### ISSUE TITLE
upside down text

### ISSUE THREAD

**Issue by mugginsjm** [AaronLiddiment/LEDMatrix#13]
Apologies for what is probably a stupid query that I can't solve. I have 2 flexible neomatrix panels and want simple scrolling. I've had some success using your examples but text is inverted. Also can you give me any pointers on simple static text.
thanks

**Comment by noycebru** [comment]
put a - in front of the matrix height

**Comment by kd8bxp** [comment]
I had a similar problem with some characters being reversed (IE: HORIZONTAL the R, Z, N, L were reverse/backwards) Putting a negative sign in front of the WIDTH appears to have fixed it - but it caused EFFECT_SCROLL_RIGHT to scroll LEFT, and EFFECT_SCROLL_LEFT to scroll RIGHT. (and I would image that left and right are now flipped for other things as well, thou I haven't tried anything else)
This problem was driving me mad, thank you for the hint to fix it.
